import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from "./provider";

=======
>>>>>>> 1505fcf (refactor artitecture setup)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Resume Analyzer",
  description: "AI-powered resume analysis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
=======
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
>>>>>>> 1505fcf (refactor artitecture setup)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 1505fcf (refactor artitecture setup)
    </html>
  );
}
